// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinWin.DataLayer.Contextes;

#nullable disable

namespace WinWin.DataLayer.Migrations
{
    [DbContext(typeof(SamroContext))]
    [Migration("20250313131910_removeImagePathFromBlogModel")]
    partial class removeImagePathFromBlogModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WinWin.DataLayer.Entities.BlogBlogGroup.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<int>("BlogGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.HasIndex("BlogGroupId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.BlogBlogGroup.BlogGroup", b =>
                {
                    b.Property<int>("BlogGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogGroupId"));

                    b.Property<string>("BlogGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("BlogGroupId");

                    b.HasIndex("ParentId");

                    b.ToTable("BlogGroups");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.RolePernissionUser.RolePermission", b =>
                {
                    b.Property<int>("RpI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RpI"));

                    b.Property<int>("PermissonId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RpI");

                    b.HasIndex("PermissonId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermisions");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.RolePernissionUser.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.Roles.Permission", b =>
                {
                    b.Property<int>("PermissonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissonId"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PermissonTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissonId");

                    b.HasIndex("ParentId");

                    b.ToTable("Permisions");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.Roles.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.Roles.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.BlogBlogGroup.Blog", b =>
                {
                    b.HasOne("WinWin.DataLayer.Entities.BlogBlogGroup.BlogGroup", "BlogGroup")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogGroup");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.BlogBlogGroup.BlogGroup", b =>
                {
                    b.HasOne("WinWin.DataLayer.Entities.BlogBlogGroup.BlogGroup", "ParentGroup")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.RolePernissionUser.RolePermission", b =>
                {
                    b.HasOne("WinWin.DataLayer.Entities.Roles.Permission", "Permisson")
                        .WithMany("RolePermisions")
                        .HasForeignKey("PermissonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinWin.DataLayer.Entities.Roles.Role", "Role")
                        .WithMany("RolePermisions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permisson");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.RolePernissionUser.UserRole", b =>
                {
                    b.HasOne("WinWin.DataLayer.Entities.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinWin.DataLayer.Entities.Roles.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.Roles.Permission", b =>
                {
                    b.HasOne("WinWin.DataLayer.Entities.Roles.Permission", null)
                        .WithMany("Permissons")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.Roles.User", b =>
                {
                    b.HasOne("WinWin.DataLayer.Entities.Roles.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.BlogBlogGroup.BlogGroup", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.Roles.Permission", b =>
                {
                    b.Navigation("Permissons");

                    b.Navigation("RolePermisions");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.Roles.Role", b =>
                {
                    b.Navigation("RolePermisions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WinWin.DataLayer.Entities.Roles.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
